// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaka6epq_rKumNi4M4xzF_l9lsiClMDzg',
    appId: '1:343924180473:web:a48c9b114495e06770e928',
    messagingSenderId: '343924180473',
    projectId: 'wishlist-3fc39',
    authDomain: 'wishlist-3fc39.firebaseapp.com',
    storageBucket: 'wishlist-3fc39.appspot.com',
    measurementId: 'G-FYDP2JC200',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbCldEz9L-AEKxWbgA4C3FHSec9j7xYs',
    appId: '1:343924180473:android:23788dddb53eff8870e928',
    messagingSenderId: '343924180473',
    projectId: 'wishlist-3fc39',
    storageBucket: 'wishlist-3fc39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBd_CeHLzr5p3PNKTujuL8B-ilVN_0FmM',
    appId: '1:343924180473:ios:b586984ee13fd98570e928',
    messagingSenderId: '343924180473',
    projectId: 'wishlist-3fc39',
    storageBucket: 'wishlist-3fc39.appspot.com',
    iosClientId: '343924180473-ep4ddfadln8v50c0103h23emor1i77ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillbox178',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBd_CeHLzr5p3PNKTujuL8B-ilVN_0FmM',
    appId: '1:343924180473:ios:b586984ee13fd98570e928',
    messagingSenderId: '343924180473',
    projectId: 'wishlist-3fc39',
    storageBucket: 'wishlist-3fc39.appspot.com',
    iosClientId: '343924180473-ep4ddfadln8v50c0103h23emor1i77ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillbox178',
  );
}
